### ISSUE TITLE
umm.... wut?

### ISSUE THREAD

**Issue by Jonak-Adipta-Kalita** [moiSentineL/dicto#13]
![image](https://github.com/user-attachments/assets/00546e81-0db5-45e9-abc1-8e9739fcda95)

**Comment by moiSentineL** [comment]
i have no idea. can you give me the steps to reproduce it?

**Comment by Jonak-Adipta-Kalita** [comment]
![image](https://github.com/user-attachments/assets/567b07dd-104b-4b23-89d6-0becbbfe3109)

with the latest commit

**Comment by Jonak-Adipta-Kalita** [comment]
https://stackoverflow.com/a/9233174 this is the fix, just tried it
